### ISSUE TITLE
Инкапсуляция - вещь, которую отдаём, должна быть взята из объекта Character, а не передана откуда-то снаружи

### ISSUE THREAD

**Issue by AlphaBeth** [kito4/lab3#3]
https://github.com/kito4/lab3/blob/1723ab9290c3fdb8c4c8e80f9c935fe77dbb8e09/src/Story.java#L26

**Comment by kito4** [comment]
public void give(Thing thing, Personage receiver) {
        list.remove(thing);
        receiver.list.add(thing);
        System.out.println(name + " отдал " + thing.name + " " + receiver.getName());
        react_to_thing(thing, receiver);
    }
